on: push

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: prenaissance

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run test:coverage
      - name: Upload test coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: "**/coverage"
  upload-codecov:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Download test coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: test-coverage
          path: "**/coverage"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
