name: Publish packages to npm
on: workflow_dispatch

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          token: ${{ secrets.NPM_TOKEN }}
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - run: pnpm publish -r --access public
